"""Embedded browser widget with an address bar -- shared by the Kibana page
and the Exploits page's production-eshop view.

Uses a dedicated QWebEngineProfile per widget instance rather than the
shared default profile: every site this app points a browser at (Kibana,
the eshop) uses a self-signed certificate, and keeping cookies/site-data
isolated per-widget is what makes "reset local score + cookies"
(page_exploits.py) actually mean something -- clearing cookies here can't
accidentally also log the user out of Kibana or anything else running in
the same process.

By default that profile is off-the-record (in-memory, unnamed) -- this is
a testing tool, not something that should accumulate browsing history/
cache between runs. Pass profile_name to get a NAMED profile instead,
which Qt persists to disk (cookies survive app restarts) -- see the Kibana
page's "Remember credentials" toggle, the one place in this app where
staying logged in across restarts is actually wanted.
"""
from __future__ import annotations

from PyQt6.QtCore import QUrl
from PyQt6.QtWebEngineCore import QWebEngineCertificateError, QWebEnginePage, QWebEngineProfile
from PyQt6.QtWebEngineWidgets import QWebEngineView
from PyQt6.QtWidgets import (
    QHBoxLayout, QLineEdit, QProgressBar, QPushButton, QVBoxLayout, QWidget,
)


class BrowserWidget(QWidget):
    def __init__(self, home_url: str = "about:blank", profile_name: str | None = None, parent=None):
        super().__init__(parent)
        self._home_url = home_url

        # A named profile gets Qt's own on-disk storage (cookies/cache
        # persisted, survives app restarts, AllowPersistentCookies by
        # default); no name keeps everything off-the-record/in-memory,
        # same as before.
        self.profile = QWebEngineProfile(profile_name, self) if profile_name else QWebEngineProfile(self)
        self.page = QWebEnginePage(self.profile, self)
        self.page.certificateError.connect(self._on_certificate_error)

        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)

        nav_row = QHBoxLayout()
        self.back_btn = QPushButton("←")
        self.back_btn.setFixedWidth(32)
        self.back_btn.setToolTip("Back")
        self.forward_btn = QPushButton("→")
        self.forward_btn.setFixedWidth(32)
        self.forward_btn.setToolTip("Forward")
        self.reload_btn = QPushButton("↻")
        self.reload_btn.setFixedWidth(32)
        self.reload_btn.setToolTip("Reload")
        self.address_bar = QLineEdit()
        self.address_bar.setPlaceholderText("Enter a URL and press Enter")
        go_btn = QPushButton("Go")
        go_btn.setFixedWidth(40)

        nav_row.addWidget(self.back_btn)
        nav_row.addWidget(self.forward_btn)
        nav_row.addWidget(self.reload_btn)
        nav_row.addWidget(self.address_bar, stretch=1)
        nav_row.addWidget(go_btn)
        layout.addLayout(nav_row)

        self.progress = QProgressBar()
        self.progress.setMaximumHeight(4)
        self.progress.setTextVisible(False)
        self.progress.setVisible(False)
        layout.addWidget(self.progress)

        self.view = QWebEngineView()
        self.view.setPage(self.page)
        layout.addWidget(self.view, stretch=1)

        self.back_btn.clicked.connect(self.view.back)
        self.forward_btn.clicked.connect(self.view.forward)
        self.reload_btn.clicked.connect(self.view.reload)
        go_btn.clicked.connect(self._navigate_to_address_bar)
        self.address_bar.returnPressed.connect(self._navigate_to_address_bar)

        self.view.urlChanged.connect(self._on_url_changed)
        self.view.loadStarted.connect(lambda: self.progress.setVisible(True))
        self.view.loadProgress.connect(self.progress.setValue)
        self.view.loadFinished.connect(lambda _ok: self.progress.setVisible(False))

        if home_url and home_url != "about:blank":
            self.navigate(home_url)

    def navigate(self, url_str: str) -> None:
        url = QUrl(url_str)
        if url.scheme() == "":
            url = QUrl("https://" + url_str)
        self.view.load(url)

    def reload_home(self) -> None:
        self.navigate(self._home_url)

    def clear_cookies(self) -> None:
        self.profile.cookieStore().deleteAllCookies()

    def _navigate_to_address_bar(self) -> None:
        self.navigate(self.address_bar.text().strip())

    def _on_url_changed(self, url: QUrl) -> None:
        self.address_bar.setText(url.toString())

    def _on_certificate_error(self, error: QWebEngineCertificateError) -> None:
        # Every site this app points a browser at (Kibana, the eshop) uses
        # a self-signed cert generated by this repo's own gen_elk_certs.sh
        # / cert pages -- there's no real CA to trust, so treat cert errors
        # for these known-self-signed local/test targets as expected
        # rather than blocking navigation on them.
        error.acceptCertificate()
