name: twin
services:
  production_eshop:
    image: wordpress:6.8.3-php8.1
    depends_on:
      - production_database
    environment:
      - WORDPRESS_DB_HOST=production_database:3306
      - WORDPRESS_DB_NAME=production_database
      - WORDPRESS_DB_USER=production_user
      - WORDPRESS_DB_PASSWORD=db_is_not_externally_exposed_but_can_be_accessed_from_this_container
    volumes:
      - ./production_eshop_files:/var/www/html
    networks:
      - production_network

  production_database:
    image: mysql:5.7
    command: bash -c "rm -f /var/lib/mysql/placeholder && docker-entrypoint.sh mysqld"
    environment:
      - MYSQL_DATABASE=production_database
      - MYSQL_USER=production_user
      - MYSQL_PASSWORD=db_is_not_externally_exposed_but_can_be_accessed_from_this_container
      - MYSQL_ROOT_PASSWORD=db_is_not_externally_exposed_but_can_be_accessed_from_this_container
    volumes:
      - ./production_database_data:/var/lib/mysql
    networks:
      - production_network

  reverse_proxy:
    image: nginx:1.27.2-alpine3.20-slim
    ports:
      - "80:80" # Temporary for testing production access
      - "8080:8080" # Temporary for testing honeypot access
      # - "443:443"
    volumes:
      - ./reverse_proxy_configuration/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - production_eshop
    networks:
      - production_network
      - honeypot_network

networks:
  production_network:
    driver: bridge
  honeypot_network:
    driver: bridge

# volumes:
#   production_wordpress__eshop_data:
#   production_mysql57__database_data:
#   honeypot_wordpress__eshop_data:
#   honeypot_mysql57__database_data:
